### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by cy-default** [huyongyong1992/vue_axios_spa#1]
朋友, 运行报错. 是什么问题. (x新手)

ERROR in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader
/lib/selector.js?type=script&index=0!./src/page/more/greenhand.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../../components/u
pLoad in E:\2014\wld_wechat_axios-master\src\page\more
 @ ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/s
elector.js?type=script&index=0!./src/page/more/greenhand.vue 19:14-48
Child html-webpack-plugin for "index.html":

**Comment by huyongyong1992** [comment]
upload组件引用出错，已解决，可以正常使用了。
