### ISSUE TITLE
关于登陆功能

### ISSUE THREAD

**Issue by wenjayliu** [huyongyong1992/vue_axios_spa#2]
我现在的项目是用token 验证登陆，前端存储token 每次请求的时候发送携带token 自定义头部的方式.

过了一下这个项目的登陆逻辑 想请教下是如何处理openid的。如果能提供具体的登陆逻辑，感激不尽 👍

**Comment by huyongyong1992** [comment]
我这在config/axios.js里封装的，放在url问号后面（公司后端要求的，如果你是放在header里也可以设置header）,token 和openId是存储在localStorage里的

**Comment by huyongyong1992** [comment]
@wenjayliu 我这在config/axios.js里封装的，放在url问号后面（公司后端要求的，如果你是放在header里也可以设置header）,token 和openId是存储在localStorage里的
