### ISSUE TITLE
router is not defined

### ISSUE THREAD

**Issue by wangq2008** [huyongyong1992/vue_axios_spa#3]
Uncaught ReferenceError: router is not defined router.js 注册全局钩子用来拦截导航 这个报错。把这个功能去掉也不能完全把所有的功能都运行通过

**Comment by huyongyong1992** [comment]
不好意思，router在router.js中未定义，现将拦截导航挪到main.js里了（vue-router在该文件中定义）

**Comment by huyongyong1992** [comment]
@wangq2008  不好意思，router在router.js中未定义，现将拦截导航挪到main.js里了（vue-router在该文件中定义）
